#!/bin/bash

IFS=\n
cpt=0


while read ligne 
do
	var1=$(echo $ligne | cut -f1 -d' ')
	var2=$(echo $ligne | cut -f2 -d' ')
	cpt=$(($cpt+`./bfsPourcent $1 $var1 $var2 | sort -d | uniq -c | grep -w "^[' ']*2" | wc -l`	))
	#echo $cpt
done < $1

echo $(($cpt/3))
